version: '3'

services:

  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_NAME=bank
      - DB_USER=bank
      - DB_PASS=12345
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A config worker -l info
    environment:
      - DB_HOST=db
      - DB_NAME=bank
      - DB_USER=bank
      - DB_PASS=12345
    volumes:
      - ./src:/app
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A config flower
    environment:
      - DB_HOST=db
      - DB_NAME=bank
      - DB_USER=bank
      - DB_PASS=12345
    volumes:
      - ./src:/app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  pgdata:
