# Generated by Django 4.2.4 on 2023-09-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_rename_account_from_transferhistory_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.account')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
